slightly fix

diff --git a/libexec/slsenv-use b/libexec/slsenv-use
--- a/libexec/slsenv-use
+++ b/libexec/slsenv-use
@@ -49,7 +49,7 @@ target_path=${SLSENV_ROOT}/versions/${version}/bin
 [ -x ${target_path}/sls ] \
   || error_and_die "Version directory for ${version} is present, but the sls binary is not executable! Manual intervention required. "
 
-info "Switching to v${version}"
-echo "${version}" > "$(slsenv-version-file)" || error_and_die "'switch to v${version} failed'"
+info "Switching to ${version}"
+echo "${version}" > "$(slsenv-version-file)" || error_and_die "'switch to ${version} failed'"
 sls --version 1>/dev/null || error_and_die "'sls --version' failed. Something is seriously wrong"
 info "Switching completed"
